### PR TITLE
Start moving the tasks over to using the unified paths config

### PR DESCRIPTION
**Pull request by bmds**
Not ready to merge yet. I'll update the styles and scripts files when those changes are merged in
cc @furzeface

### CODE REVIEW

**Comment by tawashley** [comment]
@bmds @furzeface Ignore the App Veyor issue. The config is in another ~~castle~~ branch and this is is a false positive - should only run when the config is present

**Comment by furzeface** [comment]
I'm not sure why I keep adding the label 'in progress'. Must be a [Waffle](https://waffle.io/code-computerlove/node-static-site-generator) thing :grimacing:

**Comment by bmds** [comment]
@tawashley @furzeface Added the path updates for styles and scripts now too.
Also added the missing sourcemaps for scripts in this pull request, because i'm a rebel

**Comment by tawashley** [comment]
@bmds Is this ready / safe to be merged in?

**Pull request merged**
