### PR TITLE
Feature/add initial tests

### PR DESCRIPTION
**Pull request by tawashley**
Add initial tests to check if required files / folders exist and public/build/release folders / files exists after running gulp

### CODE REVIEW

**Comment by andrewbrandwood** [comment]
Tried to test, got a TODO message

**Comment by tawashley** [comment]
Hmm, ensure you have done a fresh pull and that you are in the generatorTests folder. You will need to 'npm install' from here before running 'mocha' which will run all test files in the test directory.

Unsure as to the source of the TODO message as there are no empty tests.

**Comment by tawashley** [comment]
Global installation of mocha and gulp is preferred (and what Travis CI does)

**Comment by andrewbrandwood** [comment]
Sorry missed that.  Yep all good.

**Pull request merged**
